readings <- read.table("household_power_consumption.txt", sep=";", na.strings = "?", header = TRUE)
readings <- subset(readings, Date=="1/2/2007" | Date=="2/2/2007")
readings$DateTime <- strptime(paste(readings$Date, readings$Time), format="%d/%m/%Y %H:%M:%S")
png(filename="plot3.png")
plot(readings$DateTime, readings$Sub_metering_1, type = "l",xlab=" ",ylab="Energy sub metering")
lines(readings$DateTime, readings$Sub_metering_2, col="red")
lines(readings$DateTime, readings$Sub_metering_3, col="blue")
legend("topright", lty=1,lwd=2,col=c("black","red","blue"),legend = c("sub_metering_1", "sub_metering_2", "sub_metering_3"))
dev.off()
