readings <- read.table("household_power_consumption.txt", sep=";", na.strings = "?", header = TRUE)
readings <- subset(readings, Date=="1/2/2007" | Date=="2/2/2007")
png(filename="plot1.png")
hist(readings$Global_active_power, main = "Global Active Power", xlab = "Global Active Power (kilowatts)", col = "red")
dev.off()